"""Putting `iwantto` on PATH.

The Stemcell already prepends ``<data root>/.local/bin`` to ``PATH`` before
anything else is imported, and every manager and worker inherits that
environment. So installing the command is just a matter of writing an
executable there — and rewriting it on every boot, because a transactional
update moves the active source generation and a shim pointing at the previous
one would silently run stale code.
"""
from __future__ import annotations

import os
import stat
import sys

from helpers.paths import CODE_ROOT, DATA_ROOT

LOCAL_BIN = os.path.join(os.fspath(DATA_ROOT), ".local", "bin")
LAUNCHER_PATH = os.path.join(LOCAL_BIN, "iwantto")

_TEMPLATE = """#!{python}
# Generated by Silicon on boot. Do not edit: it is rewritten every start so it
# always points at the active source generation.
import os
import sys

sys.path.insert(0, {code_root!r})
os.environ.setdefault("SILICON_DATA_ROOT", {data_root!r})

from core.iwantto.cli import main

raise SystemExit(main())
"""


def install(*, python: str = "", code_root: str = "", data_root: str = "") -> str:
    """Write the launcher and return its path."""
    python = python or sys.executable
    code_root = code_root or os.fspath(CODE_ROOT)
    data_root = data_root or os.fspath(DATA_ROOT)

    os.makedirs(LOCAL_BIN, mode=0o700, exist_ok=True)
    contents = _TEMPLATE.format(
        python=python, code_root=code_root, data_root=data_root
    )
    # Write through a temp file so a manager cannot catch a half-written shim.
    temporary = f"{LAUNCHER_PATH}.tmp"
    with open(temporary, "w", encoding="utf-8") as handle:
        handle.write(contents)
    os.chmod(
        temporary,
        stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP,
    )
    os.replace(temporary, LAUNCHER_PATH)
    return LAUNCHER_PATH
